export const BELONGING_CREATED = 'BELONGING_CREATED';
export const BELONGING_CREATION_CONFIRMED = 'BELONGING_CREATION_CONFIRMED';
export const BELONGINGS_FETCHED = 'BELONGINGS_FETCHED';
export const BELONGINGS_RECIVED = 'BELONGINGS_RECIVED';
