export const CATEGORTY_ADDED = 'CATEGORTY_ADDED';
export const CATEGORTY_ADDITION_CONFIRMED = 'CATEGORTY_ADDITION_CONFIRMED';
export const CATEGORIES_FETCHED = 'CATEGORIES_FETCHED';
export const CATEGORIES_RECIVED = 'CATEGORIES_RECIVED';
