export const IMG_ADDED = 'IMG_ADDED';
export const IMG_REMOVED = 'IMG_REMOVED';
export const BELONGING_IMG_SENT = 'BELONGING_IMG_SENT';
export const PROFILE_IMG_SENT = 'PROFILE_IMG_SENT';
export const IMG_SENT_CONFIRMED = 'IMG_SENT_CONFIRMED';
export const IMG_SENT_FAILED = 'IMG_SENT_FAILED';
