export const OFFER_CREATED = 'OFFER_CREATED';
export const OFFER_CREATION_CONFIRMED = 'OFFER_CREATION_CONFIRMED';
export const OFFER_UPDATED = 'OFFER_UPDATED';
export const OFFER_UPDATE_CONFIRMED = 'OFFER_UPDATE_CONFIRMED';
export const OFFER_DELETED = 'OFFER_DELETED';
export const OFFER_DELETION_CONFIRMED = 'OFFER_DELETION_CONFIRMED';
export const OFFERS_FETCHED = 'OFFERS_FETCHED';
export const OFFERS_RECIVED = 'OFFERS_RECIVED';
