export const USER_CREATED = 'USER_CREATED';
export const USER_CREATION_CONFIRMED = 'USER_CREATION_CONFIRMED';
export const USER_DELETED = 'USER_DELETED';
export const USER_DELETION_CONFIRMED = 'USER_DELETION_CONFIRMED';
export const USERS_FETCHED = 'USERS_FETCHED';
export const USERS_RECIVED = 'USERS_RECIVED';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_AUTHENTICATION_CONFIRMED = 'USER_AUTHENTICATION_CONFIRMED';
